import {appearancePlan} from '../visual/appearance';
import './style.css';
import referenceManifest from '../../references/manifest.json';
import {entities,species,providers,states,assets,provenance,artDirection} from '../ontology/data';
import {resolveVisual} from '../visual/resolver';
import {Viewport} from '../rendering/viewport';
import type {EntityDescription,AssetRecord} from '../ontology/schema';

const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const escape=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let selected=entities[0],mode:'entities'|'sources'='entities',selectedAsset:AssetRecord|undefined,revision=0;let jawOverride:number|undefined;
document.querySelector('#app')!.innerHTML=`
 <header><div class="brand"><span class="mark">TV</span><div>TORN VEIL <small>VISUAL ONTOLOGY / DEVELOPMENT COMPANION</small></div></div><div class="header-right"><span class="dot"></span><span id="backend">STARTING</span><button id="references-open" class="reference-button">18 art references</button><span class="pill">ART DIRECTION &middot; ${artDirection.status}</span></div></header>
 <div class="workspace"><aside class="library"><div class="section-label">ENTITY LIBRARY <span>01</span></div><h1>What exists.<br><em>Made visible.</em></h1><p class="intro">A compositional catalog for the world of Torn Veil.</p>
 <div class="tabs"><button id="entities-tab" class="active">Ontology <b>12</b></button><button id="sources-tab">Sources <b>${assets.length}</b></button></div>
 <input id="search" placeholder="Search name, species, archetype…" aria-label="Search ontology"><select id="category" aria-label="Category"><option value="">All archetypes</option>${[...new Set(species.map(s=>s.archetype))].map(x=>`<option>${x}</option>`).join('')}</select><div id="list" class="entity-list"></div><footer class="library-footer">SIMULATION → APPEARANCE → RENDER<br><span>Rendering never owns gameplay truth.</span></footer></aside>
 <main><div class="viewport-heading"><div><div id="eyebrow" class="section-label">FINAL RENDERED INSTANCE</div><h2 id="title">Human</h2></div><span id="quality" class="badge">PROTOTYPE</span></div><div class="stage"><canvas id="viewport" aria-label="3D entity viewport"></canvas><div id="empty" class="empty" hidden><span>◇</span><h3>Geometry unresolved</h3><p>This identity is defined.<br>Its visual embodiment still needs source artwork.</p></div><div id="loading" class="loading" hidden>Loading source geometry…</div><div class="stage-label">NEUTRAL REVIEW STAGE <span>1 grid square = 1 meter</span></div><div id="dimensions" class="dimensions"></div></div>
 <div class="toolbar"><select id="view" aria-label="Review view"><option value="inspection">Inspection</option><option value="front">Front</option><option value="side">Side</option><option value="back">Back</option><option value="three-quarter">Three-quarter</option><option value="face">Face detail</option><option value="gameplay">Torn Veil gameplay &middot; 8 m</option></select><button id="reset">↺ Reset camera</button><label><input type="checkbox" id="wire"> Wireframe</label><label><input type="checkbox" id="skeleton"> Skeleton</label><select id="animation" aria-label="Animation"><option value="">Rest pose</option></select><select id="lighting" aria-label="Review lighting"><option value="neutral">Neutral light</option><option value="raking">Raking light</option></select><select id="pose" aria-label="Deformation fixture"><option value="rest">Rest pose</option><option value="shoulder">Shoulder fixture</option><option value="elbow">Elbow fixture</option><option value="hip">Hip fixture</option><option value="knee">Knee fixture</option></select><button id="pin-reference">Pin reference</button><span class="gesture">Drag to orbit · Scroll to zoom</span></div><div class="statusbar"><span id="render-status">Awaiting model</span><span>Source geometry ≠ approved art</span></div></main>
 <aside class="inspector"><div class="section-label">INSPECTOR <span>02</span></div><div id="inspector"></div></aside></div>`;
const dialog=document.createElement('dialog');dialog.id='reference-dialog';
dialog.innerHTML=`<div class="reference-heading"><div><h2>Reference evidence</h2><p>All 18 images visually inspected &middot; local guidance only &middot; rights not cleared for redistribution</p></div><button id="references-close">Close</button></div><div class="reference-grid">${referenceManifest.images.map(r=>`<article><h3>${escape(r.originalFilename)}</h3>${true?`<a href="${import.meta.env.BASE_URL}reference-images/${r.id}" target="_blank"><img loading="lazy" src="${import.meta.env.BASE_URL}reference-images/${r.id}" alt="${escape(r.originalFilename)}"></a>`:'<p>Images are available in the local development catalog only.</p>'}<p>${escape(r.observations)}</p><p class="muted">${escape(r.limitations)}</p><details><summary>Usefulness and provenance</summary><pre>${escape(JSON.stringify(r,null,2))}</pre></details></article>`).join('')}</div>`;
document.body.append(dialog);$('references-open').onclick=()=>dialog.showModal();$('references-close').onclick=()=>dialog.close();
const viewport=new Viewport($('viewport'));
const pinned=document.createElement('section');pinned.className='pinned-reference';pinned.hidden=true;pinned.innerHTML='<div><strong>Reference comparison</strong><button id="unpin-reference">Close</button></div><label>Reference <select id="reference-choice"></select></label><img id="pinned-image" alt="Pinned character reference"><p>Reference perspective and lighting differ. Model camera stays fixed; anatomy and construction require visual review.</p>';document.querySelector('main')!.append(pinned);
const referenceChoice=pinned.querySelector<HTMLSelectElement>('#reference-choice')!;
for(const r of referenceManifest.images){const option=document.createElement('option');option.value=r.id;option.textContent=r.originalFilename;referenceChoice.append(option);}
const updateReference=()=>{const id=referenceChoice.value;$<HTMLImageElement>('pinned-image').src=import.meta.env.BASE_URL+'reference-images/'+id;};
referenceChoice.value='omni';if(!referenceChoice.value)referenceChoice.selectedIndex=0;
referenceChoice.onchange=updateReference;$('pin-reference').onclick=()=>{pinned.hidden=false;updateReference();};$('unpin-reference').onclick=()=>pinned.hidden=true;
const applyPreview=()=>{const r=definition();viewport.applyAppearance(appearancePlan(selected,r.bodyAssetId),jawOverride);};
const definition=()=>resolveVisual(selected,species,providers,states);
function list(){const search=$<HTMLInputElement>('search').value.toLowerCase(),category=$<HTMLSelectElement>('category').value;const rows=mode==='entities'?entities.filter(e=>{const s=species.find(s=>s.id===e.biological.species)!;return(!category||s.archetype===category)&&JSON.stringify([e.name,e.biological,s.archetype,e.social,e.states]).toLowerCase().includes(search)}).map(e=>({id:e.id,name:e.name,sub:e.biological.species==='human'&&e.states.length?'human + vampiric':species.find(s=>s.id===e.biological.species)!.archetype,status:resolveVisual(e,species,providers,states).status})):assets.filter(a=>JSON.stringify([a.id,a.tags]).toLowerCase().includes(search)).map(a=>({id:a.id,name:a.id.replace('quaternius-','').replaceAll('-',' '),sub:a.kind,status:a.status}));
 $('list').innerHTML=rows.length?rows.map((r,i)=>`<button class="entity-row ${(mode==='entities'?selected.id:selectedAsset?.id)===r.id?'selected':''}" data-id="${escape(r.id)}"><span class="row-index">${String(i+1).padStart(2,'0')}</span><span><strong>${escape(r.name)}</strong><small>${escape(r.sub.replaceAll('_',' '))}</small></span><i class="quality-dot ${r.status==='MISSING'?'missing':''}" title="${r.status}"></i></button>`).join(''):'<p class="muted">No matching entries.</p>';
 document.querySelectorAll<HTMLButtonElement>('.entity-row').forEach(b=>b.onclick=()=>{if(mode==='entities'){selected=structuredClone(entities.find(e=>e.id===b.dataset.id)!);selectedAsset=undefined;}else selectedAsset=assets.find(a=>a.id===b.dataset.id);void show();});
}
function block(title:string,html:string){return `<section class="inspector-block"><h3>${title}</h3>${html}</section>`;}
function kv(k:string,v:unknown){return `<div class="kv"><span>${k}</span><b>${escape(v??'—')}</b></div>`;}
function inspector(){const r=definition(),a=mode==='sources'?selectedAsset:r.bodyAssetId?providers.get(r.bodyAssetId):undefined,p=a?provenance.find(p=>p.id===a.provenanceId):undefined;
 $('title').textContent=mode==='entities'?selected.name:a?.id.replace('quaternius-','')??'Source';$('eyebrow').textContent=mode==='entities'?'FINAL RENDERED INSTANCE':'SOURCE ASSET / REFERENCE';$('quality').textContent=mode==='entities'?r.status:a?.status??'MISSING';
 $('inspector').innerHTML=(mode==='entities'?block('01 / ONTOLOGY DATA',kv('Entity',selected.id)+kv('Species',selected.biological.species)+kv('Archetype',r.archetype)+kv('Sex / age',`${selected.biological.sex} / ${selected.biological.age??'n/a'}`)+(selected.biological.species==='human'?`<label>Human body study <select id="body-variant" aria-label="Human body study"><option value="male" ${selected.biological.sex==='male'?'selected':''}>Male athletic baseline</option><option value="female" ${selected.biological.sex==='female'?'selected':''}>Female athletic baseline</option></select></label>`:'')+kv('Culture',selected.social.culture)+kv('Profession',selected.social.profession)+kv('Rank',selected.gameplay.rank)+kv('States',selected.states.join(', ')||'none')+`<label class="seed-label">Appearance seed <input id="seed" type="number" min="0" max="4294967295" value="${selected.appearanceSeed}"></label><button id="vary" class="wide">Next deterministic variation</button>`)+block('APPEARANCE PREVIEW',r.bodyAssetId==='tv-human-male-v2'?'<label>Jaw width (local preview)<input id="jaw" aria-label="Jaw width" type="range" min="0" max="1" step=".01" value="'+(jawOverride??appearancePlan(selected,r.bodyAssetId).jaw)+'"></label><p class="muted">Seed applies a real jaw morph and linen/leather colors. Hair and population age remain unresolved.</p>':'<p class="muted">This asset has no authored preview variants.</p>')+block('REQUESTED / APPLIED', '<pre>'+escape(JSON.stringify({requested:appearancePlan(selected,r.bodyAssetId).requests,available:appearancePlan(selected,r.bodyAssetId).applied,applied:viewport.stats().applied,unresolved:appearancePlan(selected,r.bodyAssetId).unresolved},null,2))+'</pre>')+block('02 / VISUAL RESOLUTION',kv('Version',r.version)+kv('Fingerprint',r.fingerprint)+kv('Body',r.bodyAssetId??'UNRESOLVED')+kv('Head',r.headFamily)+kv('Material',r.materialFamily)+kv('Rig',r.rig)+kv('Hair request',r.hair)+`<details><summary>Why this appearance?</summary><ul>${r.trace.map(t=>`<li>${escape(t)}</li>`).join('')}</ul><pre>${escape(JSON.stringify(r,null,2))}</pre></details>`):block('SOURCE INSPECTION',`<p class="muted">Library reference, independent of entity identity. Rigged source files may have no animation clips.</p>`))+
 block('03 / SOURCE & PROVENANCE',p?kv('Creator',p.creator)+kv('License',p.license)+kv('Asset',a!.id)+kv('Acquired',p.downloadDate.slice(0,10))+`<a href="${escape(p.sourceUrl)}" target="_blank" rel="noopener">Official source ↗</a><details><summary>Provenance record</summary><pre>${escape(JSON.stringify(p,null,2))}</pre></details>`:'<p class="muted">No source asset assigned.</p>')+
 block('04 / UNRESOLVED REQUIREMENTS',`<ul class="requirements">${(mode==='entities'?r.unresolved:a?.limitations??['Select a source']).map(x=>`<li>${escape(x)}</li>`).join('')}</ul>`)+block('ART DIRECTION',`<p class="muted">${artDirection.status}. 18 user images inspected. Omni and Kestrel guide Human anatomy, face, plain clothing and materials. Numeric targets remain provisional; meshes are not approved. See references/manifest.json and docs/REFERENCE_ANALYSIS.md.</p><p class="muted">Lighting asset: Poly Haven · CC0</p>`);
 if(document.getElementById('jaw'))$<HTMLInputElement>('jaw').oninput=e=>{jawOverride=Number((e.target as HTMLInputElement).value);applyPreview();};
 if(mode==='entities'){if(document.getElementById('body-variant'))$<HTMLSelectElement>('body-variant').onchange=e=>{selected.biological.sex=(e.target as HTMLSelectElement).value;void show();};$<HTMLInputElement>('seed').onchange=()=>{const value=Number($<HTMLInputElement>('seed').value);if(Number.isInteger(value)&&value>=0&&value<=4294967295){selected.appearanceSeed=value;jawOverride=undefined;applyPreview();inspector();}else $('render-status').textContent='Seed must be an unsigned 32-bit integer';};$('vary').onclick=()=>{selected.appearanceSeed=(selected.appearanceSeed+1)>>>0;jawOverride=undefined;applyPreview();inspector();$('render-status').textContent='Seed applied where authored; see requested / applied requirements.';};}
}
async function show(){const token=++revision;list();inspector();const r=definition(),a=mode==='sources'?selectedAsset:r.bodyAssetId?providers.get(r.bodyAssetId):undefined;$('empty').hidden=!!a;$('loading').hidden=!a;$('dimensions').textContent='';$('render-status').textContent=a?'Loading…':'No mesh assigned · requirements remain visible';
 try{await viewport.load(a?.url,mode==='entities'?r.heightM:undefined);if(token!==revision)return;applyPreview();inspector();const stats=viewport.stats();$('dimensions').textContent=a?`${stats.dimensions.map(n=>n.toFixed(2)).join(' × ')} m`:'';$<HTMLSelectElement>('animation').innerHTML='<option value="">Rest pose</option>'+stats.animations.map(n=>`<option value="${escape(n)}">${escape(n)}</option>`).join('');$('render-status').textContent=a?`${stats.meshCount} meshes · ${stats.skeletons} skeletons · ${stats.animations.length} clips`:'No mesh assigned · identity preserved';}
 catch(e){$('render-status').textContent=`Load failed: ${e}`;$('empty').hidden=false;}finally{if(token===revision)$('loading').hidden=true;}
}
$<HTMLSelectElement>('lighting').onchange=e=>viewport.setLighting((e.target as HTMLSelectElement).value);$<HTMLSelectElement>('pose').onchange=e=>{viewport.setPose((e.target as HTMLSelectElement).value);$<HTMLSelectElement>('animation').value='';};
$('search').oninput=list;$('category').onchange=list;
for(const value of ['entities','sources'] as const)$(value+'-tab').onclick=()=>{mode=value;selectedAsset=value==='sources'?assets[0]:undefined;$(value+'-tab').classList.add('active');$((value==='sources'?'entities':'sources')+'-tab').classList.remove('active');$<HTMLInputElement>('search').value='';$<HTMLSelectElement>('category').disabled=value==='sources';void show();};
$<HTMLSelectElement>('view').onchange=e=>viewport.setView((e.target as HTMLSelectElement).value);
$('reset').onclick=()=>viewport.resetCamera();$<HTMLInputElement>('wire').onchange=e=>viewport.setWireframe((e.target as HTMLInputElement).checked);$<HTMLInputElement>('skeleton').onchange=e=>viewport.setSkeleton((e.target as HTMLInputElement).checked);$<HTMLSelectElement>('animation').onchange=e=>viewport.play((e.target as HTMLSelectElement).value);
async function start(){try{await viewport.init();viewport.setLighting('neutral');$('backend').textContent=`BABYLON 9.28 / ${viewport.backend}`;await show();}catch(err){$('render-status').textContent=`Renderer startup failed: ${err}`;console.error(err);}}void start();
// Read-only development diagnostics for browser acceptance; no simulation mutation entrypoint.
Object.defineProperty(window,'ontologyDebug',{value:{current:()=>viewport.currentMotion(),sample:(name:string,frame:number)=>viewport.reviewSample(name,frame),snapshot:()=>({mode,entityId:selected.id,sourceId:selectedAsset?.id,resolution:definition(),...viewport.stats()})}});
