import type { Occupation, Traits, Appearance } from '../core/types';

export interface CastEntry {
  key: string; name: string; gender: 'm' | 'f'; age: number; occupation: Occupation; title?: string;
  home: string; work: string | null; traits: Partial<Traits>; look: Partial<Appearance>; bio: string; wealth?: number; shift?: string; stall?: string; field?: string; hostile?: boolean;
}
const SKIN = { pale: 0xf0d5c0, fair: 0xe8c4a8, tan: 0xd9a988, olive: 0xc99a72, brown: 0xa06a45, dark: 0x6b3f2a };
const HAIR = { black: 0x1a1512, brown: 0x4a2f1a, chestnut: 0x6b3f22, blond: 0xd8b56a, red: 0xa8462a, grey: 0x9a9a9a, white: 0xe6e6e6, auburn: 0x7a3a22 };

export const CAST: CastEntry[] = [
  { key: 'garrick', name: 'Garrick Ironhand', gender: 'm', age: 46, occupation: 'smith', home: 'house_garrick', work: 'smithy', traits: { courage: 0.8, sociability: 0.45, honesty: 0.8, aggression: 0.5, greed: 0.3, piety: 0.3, loyalty: 0.9 }, look: { skin: SKIN.tan, hair: HAIR.black, shirt: 0x5a4a3a, pants: 0x2f2a26, apron: 0x6b5a48, beard: HAIR.black, build: 1.15, height: 1.06 }, bio: 'The village smith. Broad, quiet, slow to anger and slower to forgive. Took in Tomas as an apprentice after the boy was orphaned. Owes his life to Captain Rowan and never forgets it.', wealth: 80 },
  { key: 'edda', name: 'Edda Ironhand', gender: 'f', age: 44, occupation: 'cook', home: 'house_garrick', work: 'tavern', traits: { courage: 0.5, sociability: 0.85, honesty: 0.6, aggression: 0.2, greed: 0.3, piety: 0.5, curiosity: 0.8 }, look: { skin: SKIN.fair, hair: HAIR.chestnut, shirt: 0x8a3c4a, pants: 0x4a3a4a, apron: 0xe0d8c8 }, bio: "Garrick's wife, and the cook at the Gilded Boar. Knows everyone's business and considers it her duty to pass it along.", wealth: 30 },
  { key: 'tomas', name: 'Tomas Reed', gender: 'm', age: 19, occupation: 'apprentice', home: 'hut_tomas', work: 'smithy', traits: { courage: 0.55, sociability: 0.6, honesty: 0.75, aggression: 0.3, greed: 0.2, piety: 0.3, loyalty: 0.8 }, look: { skin: SKIN.fair, hair: HAIR.brown, shirt: 0x6a6a8a, pants: 0x3a3a3a, apron: 0x5a4a3a, height: 1.0, build: 0.95 }, bio: "Garrick's apprentice, orphaned young. Earnest and a little clumsy. Sweet on Mara, the baker's daughter, to her father's displeasure.", wealth: 8 },
  { key: 'osric', name: 'Osric Bramble', gender: 'm', age: 52, occupation: 'baker', home: 'bakery', work: 'bakery', traits: { courage: 0.4, sociability: 0.5, honesty: 0.7, aggression: 0.35, greed: 0.5, piety: 0.6 }, look: { skin: SKIN.pale, hair: HAIR.grey, shirt: 0xe8e0d0, pants: 0x6a5a4a, apron: 0xf0ece0, build: 1.1, beard: HAIR.grey }, bio: 'The baker, a widower who raised his daughter Mara alone. Proud, protective, and convinced Tomas Reed is not good enough for her.', wealth: 60 },
  { key: 'mara', name: 'Mara Bramble', gender: 'f', age: 18, occupation: 'baker', home: 'bakery', work: 'bakery', stall: 'stall_bread', traits: { courage: 0.35, sociability: 0.75, honesty: 0.85, aggression: 0.1, greed: 0.2, piety: 0.5, curiosity: 0.7 }, look: { skin: SKIN.fair, hair: HAIR.auburn, shirt: 0x4a7a5a, pants: 0x7a5a4a, apron: 0xf0ece0, height: 0.96, build: 0.9 }, bio: "The baker's daughter. Sells bread at the morning market and knows every child's name. In love with Tomas Reed.", wealth: 12 },
  { key: 'hilda', name: 'Hilda Vance', gender: 'f', age: 41, occupation: 'innkeeper', home: 'tavern', work: 'tavern', traits: { courage: 0.65, sociability: 0.9, honesty: 0.6, aggression: 0.4, greed: 0.55, curiosity: 0.7 }, look: { skin: SKIN.tan, hair: HAIR.red, shirt: 0x8a2a2a, pants: 0x3a2a2a, apron: 0xd8d0c0, build: 1.05 }, bio: 'Keeper of the Gilded Boar. Loud, warm, and sharp with money. Nothing said in her tavern escapes her.', wealth: 150 },
  { key: 'bram', name: 'Bram Vance', gender: 'm', age: 45, occupation: 'innkeeper', home: 'tavern', work: 'tavern', traits: { courage: 0.6, sociability: 0.5, honesty: 0.65, aggression: 0.3, greed: 0.4 }, look: { skin: SKIN.olive, hair: HAIR.brown, shirt: 0x4a3a2a, pants: 0x2a2a2a, apron: 0x7a6a5a, build: 1.15, beard: HAIR.brown }, bio: "Hilda's husband. Brews the ale, taps the barrels, throws out the drunks. A man of few words and a heavy hand.", wealth: 60 },
  { key: 'ysolde', name: 'Ysolde Vance', gender: 'f', age: 17, occupation: 'server', home: 'tavern', work: 'tavern', traits: { courage: 0.45, sociability: 0.8, honesty: 0.5, aggression: 0.2, curiosity: 0.9 }, look: { skin: SKIN.tan, hair: HAIR.red, shirt: 0x6a4a8a, pants: 0x4a3a3a, apron: 0xd8d0c0, height: 0.95, build: 0.88 }, bio: "The innkeepers' daughter. Serves at the Boar and collects rumours like other girls collect ribbons.", wealth: 10 },
  { key: 'wendel', name: 'Wendel Crane', gender: 'm', age: 50, occupation: 'merchant', home: 'house_wendel', work: 'store', traits: { courage: 0.3, sociability: 0.6, honesty: 0.4, aggression: 0.3, greed: 0.9, piety: 0.3 }, look: { skin: SKIN.pale, hair: HAIR.grey, shirt: 0x2a4a7a, pants: 0x2a2a3a, hatStyle: 'cap', hat: 0x2a4a7a, build: 1.05 }, bio: 'Owner of the general store. Counts every coin twice. Keeps a ledger of who owes him what, and Fenn Muddle is at the top of it.', wealth: 220 },
  { key: 'petra', name: 'Petra Crane', gender: 'f', age: 47, occupation: 'merchant', home: 'house_wendel', work: 'store', traits: { courage: 0.4, sociability: 0.7, honesty: 0.45, aggression: 0.4, greed: 0.6, piety: 0.7, curiosity: 0.7 }, look: { skin: SKIN.pale, hair: HAIR.blond, shirt: 0x7a6a3a, pants: 0x4a4a3a }, bio: "Wendel's wife. Pious, suspicious, and the source of most of what the village believes about Old Wyn.", wealth: 40 },
  { key: 'aldous', name: 'Father Aldous', gender: 'm', age: 63, occupation: 'priest', title: 'Father', home: 'chapel', work: 'chapel', traits: { courage: 0.5, sociability: 0.7, honesty: 0.9, aggression: 0.05, greed: 0.1, piety: 1.0, loyalty: 0.7 }, look: { skin: SKIN.pale, hair: HAIR.white, shirt: 0x3a3a3a, pants: 0x3a3a3a, hatStyle: 'hood', hat: 0x3a3a3a, build: 0.95 }, bio: 'The priest of the Lantern-Bearer. Gentle and stubborn. Has buried half the village and married the other half.', wealth: 15 },
  { key: 'ione', name: 'Sister Ione', gender: 'f', age: 29, occupation: 'acolyte', title: 'Sister', home: 'chapel', work: 'chapel', traits: { courage: 0.6, sociability: 0.55, honesty: 0.85, aggression: 0.1, greed: 0.1, piety: 0.9, curiosity: 0.6 }, look: { skin: SKIN.brown, hair: HAIR.black, shirt: 0x5a5a6a, pants: 0x3a3a4a, hatStyle: 'hood', hat: 0x5a5a6a, build: 0.9 }, bio: "Father Aldous's acolyte. Tends the graves and the sick. Came from the city and does not speak of why.", wealth: 8 },
  { key: 'rowan', name: 'Rowan Ashford', gender: 'm', age: 38, occupation: 'captain', title: 'Captain', home: 'house_rowan', work: 'guardhouse', traits: { courage: 0.95, sociability: 0.5, honesty: 0.85, aggression: 0.45, greed: 0.2, piety: 0.4, loyalty: 0.9 }, look: { skin: SKIN.tan, hair: HAIR.brown, shirt: 0x8a2a2a, pants: 0x3a3a3a, hatStyle: 'helm', hat: 0x8a8a90, build: 1.1, height: 1.05, beard: HAIR.brown }, bio: 'Captain of the village watch. Old soldier, straight-backed. Carries Oathkeeper, the sword Garrick forged for him. Believes in the law more than in people.', wealth: 90 },
  { key: 'hale', name: 'Hale Dorn', gender: 'm', age: 27, occupation: 'guard', home: 'guardhouse', work: 'guardhouse', shift: 'day', traits: { courage: 0.7, sociability: 0.65, honesty: 0.7, aggression: 0.4, loyalty: 0.75 }, look: { skin: SKIN.fair, hair: HAIR.blond, shirt: 0x8a2a2a, pants: 0x3a3a3a, hatStyle: 'helm', hat: 0x8a8a90, build: 1.05 }, bio: 'A young guard on the day watch. Keen, decent, and hopelessly sweet on Ysolde Vance.', wealth: 25 },
  { key: 'dunstan', name: 'Dunstan Mole', gender: 'm', age: 34, occupation: 'guard', home: 'guardhouse', work: 'guardhouse', shift: 'night', traits: { courage: 0.6, sociability: 0.4, honesty: 0.5, aggression: 0.55, greed: 0.5, loyalty: 0.5 }, look: { skin: SKIN.olive, hair: HAIR.black, shirt: 0x8a2a2a, pants: 0x3a3a3a, hatStyle: 'helm', hat: 0x8a8a90, build: 1.1, beard: HAIR.black }, bio: 'Night watchman. Drinks more than he should and Hilda has told him so. Not a bad man, but a tired one.', wealth: 20 },
  { key: 'brigid', name: 'Brigid Tallow', gender: 'f', age: 30, occupation: 'guard', home: 'guardhouse', work: 'guardhouse', shift: 'late', traits: { courage: 0.85, sociability: 0.5, honesty: 0.8, aggression: 0.5, loyalty: 0.8 }, look: { skin: SKIN.brown, hair: HAIR.black, shirt: 0x8a2a2a, pants: 0x3a3a3a, hatStyle: 'helm', hat: 0x8a8a90, build: 1.0, height: 1.03 }, bio: 'Guard on the late watch. The best fighter in the village after the captain, and she knows it.', wealth: 30 },
  { key: 'alwin', name: 'Alwin Hollis', gender: 'm', age: 39, occupation: 'farmer', home: 'farmhouse_alwin', work: 'farm_alwin', traits: { courage: 0.5, sociability: 0.5, honesty: 0.8, aggression: 0.25, greed: 0.3, piety: 0.6 }, look: { skin: SKIN.tan, hair: HAIR.brown, shirt: 0x6a7a4a, pants: 0x5a4a3a, hatStyle: 'wide', hat: 0xb09a60 }, bio: 'Farms the western fields. Steady and unremarkable, which in a village is a kind of virtue.', wealth: 35 },
  { key: 'greta', name: 'Greta Hollis', gender: 'f', age: 37, occupation: 'farmer', home: 'farmhouse_alwin', work: 'farm_alwin', stall: 'stall_produce', field: 'farm_alwin', traits: { courage: 0.5, sociability: 0.8, honesty: 0.75, aggression: 0.3, greed: 0.4, piety: 0.6, curiosity: 0.6 }, look: { skin: SKIN.fair, hair: HAIR.blond, shirt: 0x9a6a3a, pants: 0x5a4a3a, apron: 0xe0d8c8 }, bio: "Alwin's wife. Sells vegetables at the morning market and worries about Pip.", wealth: 20 },
  { key: 'pip', name: 'Pip Hollis', gender: 'm', age: 9, occupation: 'child', home: 'farmhouse_alwin', work: null, traits: { courage: 0.6, sociability: 0.9, honesty: 0.6, aggression: 0.2, curiosity: 1.0 }, look: { skin: SKIN.fair, hair: HAIR.blond, shirt: 0x4a6a9a, pants: 0x5a4a3a, height: 0.62, build: 0.75 }, bio: 'The Hollis boy. Everywhere at once, into everything, afraid of nothing except Old Wyn.', wealth: 0 },
  { key: 'jory', name: 'Jory Fletcher', gender: 'm', age: 44, occupation: 'farmer', home: 'house_jory', work: 'farm_jory', traits: { courage: 0.55, sociability: 0.6, honesty: 0.7, aggression: 0.35, greed: 0.35 }, look: { skin: SKIN.olive, hair: HAIR.chestnut, shirt: 0x7a6a4a, pants: 0x3a3a2a, hatStyle: 'wide', hat: 0x8a7a50, beard: HAIR.chestnut }, bio: 'Farms the south-eastern fields with his wife Nell. Fond of a drink and a song.', wealth: 40 },
  { key: 'nell', name: 'Nell Fletcher', gender: 'f', age: 42, occupation: 'farmer', home: 'house_jory', work: 'farm_jory', stall: 'stall_grain', field: 'farm_jory', traits: { courage: 0.5, sociability: 0.7, honesty: 0.8, aggression: 0.2, piety: 0.7 }, look: { skin: SKIN.olive, hair: HAIR.black, shirt: 0x5a3a5a, pants: 0x4a3a3a, apron: 0xe0d8c8 }, bio: "Jory's wife and Maud Penny's daughter. Sells grain at the market. Practical to the bone.", wealth: 25 },
  { key: 'tilly', name: 'Tilly Fletcher', gender: 'f', age: 8, occupation: 'child', home: 'house_jory', work: null, traits: { courage: 0.4, sociability: 0.8, honesty: 0.8, curiosity: 0.9 }, look: { skin: SKIN.olive, hair: HAIR.black, shirt: 0x9a5a7a, pants: 0x5a4a3a, height: 0.6, build: 0.72 }, bio: "The Fletchers' girl. Pip's best friend and conscience.", wealth: 0 },
  { key: 'cedric', name: 'Cedric Wold', gender: 'm', age: 58, occupation: 'farmer', home: 'house_cedric', work: 'farm_cedric', traits: { courage: 0.5, sociability: 0.25, honesty: 0.85, aggression: 0.2, greed: 0.2, piety: 0.7 }, look: { skin: SKIN.pale, hair: HAIR.grey, shirt: 0x4a4a4a, pants: 0x3a3a3a, beard: HAIR.grey, build: 0.95 }, bio: 'A widower. His wife Anna died last winter and he has not been the same since. Works his fields alone and visits her grave every evening. Her ring was lost the day she died.', wealth: 30 },
  { key: 'maud', name: 'Maud Penny', gender: 'f', age: 66, occupation: 'farmer', home: 'house_maud', work: 'farm_maud', traits: { courage: 0.7, sociability: 0.6, honesty: 0.9, aggression: 0.5, greed: 0.3, piety: 0.5 }, look: { skin: SKIN.pale, hair: HAIR.white, shirt: 0x6a5a6a, pants: 0x4a4a4a, hatStyle: 'wide', hat: 0x9a8a60, build: 0.9, height: 0.94 }, bio: "Nell's mother, still working her own fields at sixty-six. Says exactly what she thinks, to anyone, at any volume.", wealth: 45 },
  { key: 'hobb', name: 'Hobb Grist', gender: 'm', age: 49, occupation: 'miller', home: 'mill', work: 'mill', traits: { courage: 0.35, sociability: 0.35, honesty: 0.6, aggression: 0.4, greed: 0.6 }, look: { skin: SKIN.tan, hair: HAIR.brown, shirt: 0xd8d0c0, pants: 0x6a5a4a, build: 1.12, beard: HAIR.brown }, bio: 'The miller. Was robbed on the east road twelve days ago by two bandits and has not stopped talking about it.', wealth: 70 },
  { key: 'kestrel', name: 'Kestrel', gender: 'f', age: 33, occupation: 'hunter', home: 'hut_kestrel', work: 'forest_north', stall: 'stall_game', traits: { courage: 0.85, sociability: 0.3, honesty: 0.7, aggression: 0.5, greed: 0.3, curiosity: 0.6 }, look: { skin: SKIN.brown, hair: HAIR.black, shirt: 0x3a4a2a, pants: 0x2a3a2a, hatStyle: 'hood', hat: 0x3a4a2a, build: 0.92, height: 1.02 }, bio: 'The hunter. Lives at the forest edge and sells venison in the afternoons. Has seen the bandit camp and told the captain where it is.', wealth: 30 },
  { key: 'wyn', name: 'Old Wyn', gender: 'f', age: 71, occupation: 'herbalist', home: 'hut_wyn', work: 'river_woods', traits: { courage: 0.6, sociability: 0.3, honesty: 0.8, aggression: 0.2, greed: 0.1, piety: 0.2, curiosity: 0.8 }, look: { skin: SKIN.pale, hair: HAIR.white, shirt: 0x3a3a4a, pants: 0x2a2a2a, hatStyle: 'hood', hat: 0x2a2a3a, build: 0.85, height: 0.9 }, bio: 'The herbalist who lives alone in the south-western woods. Half the village thinks she is a witch. She has found things at the old shrine that others have lost.', wealth: 10 },
  { key: 'bors', name: 'Bors Ashwood', gender: 'm', age: 41, occupation: 'woodcutter', home: 'house_bors', work: 'clearing', traits: { courage: 0.75, sociability: 0.5, honesty: 0.5, aggression: 0.75, greed: 0.5, piety: 0.2 }, look: { skin: SKIN.tan, hair: HAIR.red, shirt: 0x8a5a2a, pants: 0x3a3a3a, build: 1.2, height: 1.08, beard: HAIR.red }, bio: 'The woodcutter. Big, loud, quick with his fists. Has a long-running feud with Garrick over timber money and a longer one with sobriety.', wealth: 25 },
  { key: 'godwin', name: 'Elder Godwin', gender: 'm', age: 70, occupation: 'elder', title: 'Elder', home: 'house_godwin', work: null, traits: { courage: 0.5, sociability: 0.7, honesty: 0.8, aggression: 0.1, greed: 0.3, piety: 0.6, loyalty: 0.7 }, look: { skin: SKIN.olive, hair: HAIR.white, shirt: 0x5a4a7a, pants: 0x3a3a3a, beard: HAIR.white, build: 0.95, height: 0.97 }, bio: 'The village elder. Settles disputes, remembers everything, and is listened to by everyone including the captain.', wealth: 100 },
  { key: 'fenn', name: 'Fenn Muddle', gender: 'm', age: 36, occupation: 'vagrant', home: 'tavern', work: null, traits: { courage: 0.3, sociability: 0.6, honesty: 0.4, aggression: 0.2, greed: 0.5, piety: 0.2 }, look: { skin: SKIN.tan, hair: HAIR.brown, shirt: 0x5a5a4a, pants: 0x4a4a3a, beard: HAIR.brown, build: 0.9 }, bio: 'Once a soldier alongside Rowan; now a drunk who sleeps on a bench at the Boar. Owes Wendel Crane twenty silver and avoids him accordingly.', wealth: 2 },
  { key: 'skarn', name: 'Skarn', gender: 'm', age: 40, occupation: 'bandit', home: 'camp', work: 'camp', hostile: true, traits: { courage: 0.8, sociability: 0.3, honesty: 0.1, aggression: 0.9, greed: 0.9, loyalty: 0.4 }, look: { skin: SKIN.olive, hair: HAIR.black, shirt: 0x2a2a2a, pants: 0x3a2a2a, hatStyle: 'hood', hat: 0x2a2a2a, build: 1.15, height: 1.05, beard: HAIR.black }, bio: 'Leader of the two bandits camped in the north-eastern forest. Robbed Hobb the miller on the east road.', wealth: 60 },
  { key: 'vex', name: 'Vex', gender: 'f', age: 28, occupation: 'bandit', home: 'camp', work: 'camp', hostile: true, traits: { courage: 0.7, sociability: 0.4, honesty: 0.2, aggression: 0.8, greed: 0.8, loyalty: 0.6 }, look: { skin: SKIN.pale, hair: HAIR.red, shirt: 0x3a2a3a, pants: 0x2a2a2a, hatStyle: 'hood', hat: 0x3a2a3a, build: 0.92 }, bio: "Skarn's partner. Quicker than him, and meaner.", wealth: 30 },
];
