// Generated by scripts/generate-interaction-spec.ts. Do not edit.
#pragma once
namespace TVCombatRepertoire {
struct FMove {const TCHAR* Id;const TCHAR* Variant;const TCHAR* Asset;const TCHAR* Effector;double preparation;double active;double recovery;double samplePreparation;double sampleActive;double sampleRecovery;double attackAt;double stepAt;double postureAt;double moveAt;};
inline const FMove& Move(const FString& Id) {
 static const FMove Moves[]={{TEXT("jab"),TEXT("direct"),TEXT("/Game/TornVeil/Combat/Refinement/Animations/A_TV_JabRefined"),TEXT("middle_01_l"),0.26,0.15,0.27,0.3,0.15,0.3,0.43,0.47,0.49,0.49},{TEXT("cross"),TEXT("hook"),TEXT("/Game/TornVeil/Combat/Repair/Animations/A_TV_Cross"),TEXT("middle_01_r"),0.28,0.15,0.29,0.3,0.15,0.3,0.47,0.49,0.53,0.53},{TEXT("front_kick"),TEXT("kick"),TEXT("/Game/TornVeil/Combat/Repair/Animations/A_TV_Kick"),TEXT("foot_r"),0.3,0.15,0.3,0.3,0.15,0.3,0.63,0.65,0.68,0.65},{TEXT("round_kick"),TEXT("round"),TEXT("/Game/TornVeil/Combat/Refinement/Animations/A_TV_RoundKick"),TEXT("foot_r"),0.32,0.2,0.28,0.32,0.2,0.28,0.7,0.7,0.75,0.7}};
 for(const auto& M:Moves)if(Id==M.Id)return M;return Moves[0];
}
}
