// Generated by scripts/generate-interaction-spec.ts. Do not edit.
#pragma once
namespace TVInteractionSpec {
inline constexpr const TCHAR* revision = TEXT("tv-interaction-1");
inline constexpr double stepSeconds = 0.016666666666666666;
inline constexpr double sprintMultiplier = 1.55;
inline constexpr double radius = 0.3;
inline constexpr double height = 1.75;
inline constexpr double stepHeight = 1.05;
inline constexpr double sweepStep = 0.1;
inline constexpr double inputHorizonSeconds = 0.25;
inline constexpr double preparationSeconds = 0.3;
inline constexpr double activeSeconds = 0.15;
inline constexpr double recoverySeconds = 0.3;
inline constexpr double sidestepMetres = 1.05;
inline constexpr double backstepMetres = 0.85;
inline constexpr double defenseSeconds = 0.3;
inline constexpr double defenseRecoverySeconds = 0.3;
inline constexpr double duckHeight = 0.9;
inline constexpr const TCHAR* hash = TEXT("b3c795a42e4ec695a86dbcb061d41d6de5c4fe94b85d880e431b10ccda0406e8");
}
