// Generated by scripts/generate-interaction-spec.ts. Do not edit.
#pragma once
namespace TVInteractionSpec {
inline constexpr const TCHAR* revision = TEXT("tv-interaction-4");
inline constexpr double unarmedPathReach = 0.9;
inline constexpr double stepSeconds = 0.016666666666666666;
inline constexpr double sprintMultiplier = 1.55;
inline constexpr double radius = 0.3;
inline constexpr double height = 1.75;
inline constexpr double stepHeight = 1.05;
inline constexpr double sweepStep = 0.1;
inline constexpr double inputHorizonSeconds = 0.25;
inline constexpr double preparationSeconds = 0.3;
inline constexpr double activeSeconds = 0.15;
inline constexpr double recoverySeconds = 0.3;
inline constexpr double sidestepMetres = 0.65;
inline constexpr double backstepMetres = 0.55;
inline constexpr double defenseSeconds = 0.24;
inline constexpr double defenseRecoverySeconds = 0.12;
inline constexpr double attackChainSeconds = 0.03;
inline constexpr double attackEvadeSeconds = 0.06;
inline constexpr double combatBufferSeconds = 0.25;
inline constexpr double dodgeDeadZone = 0.2;
inline constexpr double defenseEffort = 0.035;
inline constexpr double duckRecoveryAt = 0.38;
inline constexpr double duckSeconds = 0.5833333333333334;
inline constexpr double duckHeight = 1.33;
inline constexpr double facingRadiansPerSecond = 12.566370614359172;
inline constexpr double crouchEnterSeconds = 0.18;
inline constexpr double crouchExitSeconds = 0.22;
inline constexpr double crouchSpeedMultiplier = 0.45;
inline constexpr double crouchEffort = 0.012;
inline constexpr double heldInputSeconds = 0.25;
inline constexpr const TCHAR* hash = TEXT("19a85ee30c33b89a18747e8cb18963ba30acc6026abb954460f8d3186138f1d4");
}
