// Authoring record: every entry below was visually inspected, not classified by filename alone.
import {readFileSync,writeFileSync} from 'node:fs';
const observations={
 'omni':['character','Primary male Human: athletic adult, credible head/hands, strong jaw, stubble and swept dirty-blond hair. Cream linen shirt, dark fitted trousers, worn belt and calf boots.','Perspective and shirt hide precise anatomy; attractive individual face and hair are not a universal population template.',[3,3,0,3,2,3,0,3,0,1,3]],
 'kestrel':['character','Primary female Human: athletic with readable waist/hips; natural freckles and face, loose braid, cream lace-up blouse, dark trousers, leather boots.','Neckline, attractiveness, skin tone and braid belong to this individual; do not mandate these for all women.',[3,0,3,3,2,3,0,3,0,1,3]],
 'kestrel character sheet':['character','Best Human modeling guide: front/side/back/three-quarter, face and clothing detail; linen weave, seams, leather cuffs.','Not a registered orthographic turnaround. Bun versus loose braid, neckline and boot construction drift. Embedded origin/height/biography are character annotations, not canonical simulation facts.',[3,0,3,3,2,3,0,3,0,3,2]],
 'female orc':['character','Female Orc anatomy and head sheet: powerful athletic limbs, pointed ears, small tusks, olive skin, dark tied hair; multiple views.','Near-duplicate design of female row in dimorphism sheet; gloss, tusks and hair vary. Minimal wraps are anatomy visibility aids, not the ordinary wardrobe.',[2,0,3,3,2,1,0,3,0,3,1]],
 'orcish dimorphism':['character','Male/female Orc comparison: male broad chest, traps and jaw, relatively short legs, large hands and tusks; female less extreme, muscular with smaller tusks.','Strong authored dimorphism is a design proposal, not inferred biology mechanics. Height captions are reference annotations. More exaggerated male than village variants.',[2,3,3,3,2,1,0,3,0,3,1]],
 'orc1':['character','Clothed Orc: weathered gray-olive skin, heavy brow, tusks and blunt face; hunched broad frame, layered coarse wraps and rough weapon.','Clothing obscures torso; gray hue and posture differ from orc2. Poverty, violence and primitive equipment are individual context, not species truth.',[2,2,0,3,2,2,0,3,0,1,3]],
 'orc2':['character','Bare-torso male Orc: broad muscular body, brown-olive weathered skin, thick neck, broad nose, tusks and long dark hair; useful hands/limb volumes.','Perspective exaggerates near hand/foot; build differs from studio sheet. Shares scene and pose with armored version.',[2,3,0,3,3,1,0,3,0,2,3]],
 'orc armered':['armor','Armored variant of orc2: segmented weathered iron, coarse leather and chain, substantial shoulder protection.','Preserve original misspelled filename in provenance. Armor hides anatomy; spike language is this kit, not every Orc culture.',[2,1,0,2,2,1,3,3,0,1,3]],
 'omni armor':['armor','Human armor/material target: fitted articulated plate, controlled bright metal edges, cloth underlayers, leather closures; visible male face/hair.','Near-duplicate outfit family with full armor. Heraldry and cross motifs vary and are not automatically Torn Veil religion/faction requirements.',[3,1,0,3,1,2,3,2,0,1,3]],
 'omni full armor':['armor','Enclosed helmet and full Human plate silhouette; neck/shoulder overlaps, plume and tabard, physically legible metal/leather layering.','Helmet occludes face. Tree/animal heraldry and chest ornament differ from open-head variant; exact kit is unsettled.',[2,1,0,0,1,2,3,2,0,1,3]],
 'goblin plain':['creature','Small wiry humanoid with oversized ears/head, long thin fingers, low bent posture and lean limbs; rag clothing with tactile texture.','Outside Human milestone. Same scene/pose family as armored goblin. Creature exaggeration should not transfer to Human proportions.',[2,2,0,3,3,2,0,3,3,1,3]],
 'goblin armored':['armor','Goblin armor variant: patchwork leather, small plates and chain over wiry silhouette; long fingers and ears remain legible.','Semantic near-duplicate of plain goblin with face and outfit changes; not an independent vote for global anatomy.',[2,1,0,3,3,2,3,3,3,1,3]],
 'lich1':['creature','Skeletal caster with crown, deeply layered decayed embroidered robes, dark bone/metal, purple magic accents.','Staff shape, trim and color change across lich variants; emission is state/equipment-specific, not general lighting.',[2,0,0,2,2,3,2,2,3,1,3]],
 'lich2':['creature','Alternative skeletal caster: narrow vertical silhouette, burgundy ragged robes and spiked metal, purple-blue eye/hand/staff glow.','Closely related composition to lich1; ornamental density and robe colors are alternatives rather than a single definitive kit.',[2,0,0,2,2,3,2,2,3,1,3]],
 'lich3':['creature','Lich with staff in opposite hand, round blue focal jewel, skull, layered robes and worn armor.','Handedness, magic color, staff topology and emblems differ from lich1/2. Preserve variants without resolving invented lore.',[2,0,0,2,2,3,2,2,3,1,3]],
 'skelly knight':['armor','Skeletal knight with exposed limb bones, dented plate, chain, rag tabard, sword and shield; strong state-plus-equipment example.','Bone joints in one illustration do not provide a rig specification. Heraldry is incidental. Outside current humanoid build scope.',[2,0,0,2,2,2,3,2,3,1,3]],
 'iguana hydra':['creature','Creature sheet: colorful orange spines, broad armored iguana heads, multiple necks, scale/eye/foot details and silhouette views.','More stylized, saturated and chunky than perentie hydra. View-to-view head counts/neck branching are not reliable topology; text about powers/habitat is not simulation authority.',[2,0,0,0,0,0,0,3,3,3,2]],
 'perentie hydra':['creature','Naturalistic monitor-lizard hydra, narrow heads and necks, subdued spotted scales, close-up eye/mouth/foot detail and multi-view silhouette.','Alternative creature family to iguana hydra; do not average their head/spine/saturation language. Pose views are illustrative, not calibrated orthographic.',[3,0,0,0,0,0,0,3,3,3,2]]
};
const categories=['overallArtDirection','maleAnatomy','femaleAnatomy','face','hands','clothing','armor','species','creature','turnaroundModeling','gameplayView'];
const inventory=JSON.parse(readFileSync('generated/reference-inspection/inventory.json','utf8'));
const images=inventory.map(f=>{const [folder,observationsText,limitations,scores]=observations[f.filename];const slug=f.filename.replaceAll(' ','-');return {id:slug,originalFilename:f.filename,sourceRoot:'%USERPROFILE%/Desktop/projects/character-models',localPath:`references/${folder}/${slug}.png`,sha256:f.sha256,bytes:f.bytes,format:f.format,width:f.width,height:f.height,creator:'Unknown; supplied by user',license:'USER_PROVIDED_REFERENCE_ONLY',redistribution:'Not cleared; local visual guidance only. Never stage under public/assets.',modificationStatus:'Unmodified byte-identical copy; extension added to copy only',visuallyInspected:true,inspectionDate:'2026-10-04',usefulness:Object.fromEntries(categories.map((k,i)=>[k,scores[i]])),observations:observationsText,limitations};});
const manifest={schemaVersion:1,role:'Primary Torn Veil visual reference source; does not define mechanical truth',ratingScale:{0:'not useful',1:'context only',2:'supporting',3:'primary'},exactDuplicateGroups:[],relatedVariantGroups:[['omni','omni armor','omni full armor'],['kestrel','kestrel character sheet'],['female orc','orcish dimorphism'],['orc2','orc armered'],['goblin plain','goblin armored'],['lich1','lich2','lich3']],images};
writeFileSync('references/manifest.json',JSON.stringify(manifest,null,2)+'\n');
writeFileSync('references/INVENTORY.md','# Visually reviewed reference inventory\n\nAll 18 source files are extensionless PNG images. No exact SHA-256 duplicates. Source originals remain untouched. Local copies retain exact bytes and are excluded from Git and public asset staging. See [manifest.json](manifest.json) for dimensions, hashes, provenance and all eleven usefulness ratings.\n\n'+images.map(e=>`## ${e.originalFilename}\n\n[Local image](${e.localPath.replace('references/','')}) · ${e.width} × ${e.height}\n\n${e.observations}\n\n**Limits:** ${e.limitations}\n\n**Primary uses:** ${Object.entries(e.usefulness).filter(([,s])=>s===3).map(([k])=>k).join(', ')}.\n`).join('\n'));
