import {describe,it,expect} from 'vitest';
import {entities,species,providers,states,assets,provenance,artDirection} from '../src/ontology/data';
import {EntitySchema,AssetSchema,ArtDirectionSchema} from '../src/ontology/schema';
import {resolveVisual} from '../src/visual/resolver';
import raw from '../ontology/raw/vocabulary.json';
import archetypes from '../ontology/archetypes/index.json';
describe('compositional ontology',()=>{
 it('preserves all original vocabulary and multiaxis classification',()=>{expect(raw).toHaveLength(230);expect(raw[0].term).toBe('Humans');expect(raw[229].term).toBe('Transcendent Entities');expect(raw.every(e=>e.categories.length>0)).toBe(true);expect(raw.find(e=>e.term==='Vampires')!.categories).toContain('supernatural_states');expect(archetypes).toHaveLength(16);});
 it('validates twelve definitions and rejects malformed units/seeds',()=>{expect(entities).toHaveLength(12);for(const e of entities)expect(EntitySchema.safeParse(e).success).toBe(true);expect(EntitySchema.safeParse({...entities[0],appearanceSeed:-1}).success).toBe(false);expect(EntitySchema.safeParse({...entities[0],biological:{...entities[0].biological,heightM:0}}).success).toBe(false);expect(EntitySchema.safeParse({...entities[0],gameplay:{damage:400}}).success).toBe(false);});
 it('keeps culture independent of species and vampire a human state',()=>{const vampire=entities.find(e=>e.name==='Vampire')!;expect(vampire.biological.species).toBe('human');expect(vampire.states).toContain('vampiric');for(const id of ['human','elf','orc']){const r=resolveVisual({...entities[0],biological:{species:id},social:{culture:'dunmere'}},species,providers,states);expect(r.clothing).toContain('dunmere:wardrobe');}});
 it('is deterministic, pure, state-order invariant and seed sensitive',()=>{const e=structuredClone(entities[0]);e.states=['undead','vampiric'];const before=JSON.stringify(e);const a=resolveVisual(e,species,providers,states);expect(resolveVisual(e,species,providers,states)).toEqual(a);expect(resolveVisual({...e,states:[...e.states].reverse()},species,providers,states)).toEqual(a);expect(JSON.stringify(e)).toBe(before);expect(resolveVisual({...e,appearanceSeed:e.appearanceSeed+1},species,providers,states).morphology).not.toEqual(a.morphology);});
 it('fails unknown species and exposes missing visuals',()=>{expect(()=>resolveVisual({...entities[0],biological:{species:'not-registered'}},species,providers)).toThrow('Unknown species');expect(resolveVisual(entities.find(e=>e.name==='Dragon'),species,providers,states).status).toBe('MISSING');const r=resolveVisual({...entities[0],states:['future-state']},species,providers,states);expect(r.unresolved).toContain('State visual rule: future-state');});
 it('requires provenance and human evidence for approved quality',()=>{expect(new Set(assets.map(a=>a.id)).size).toBe(assets.length);for(const a of assets){expect(providers.get(a.id)).toEqual(a);expect(provenance.some(p=>p.id===a.provenanceId)).toBe(true);expect(AssetSchema.safeParse({...a,status:'PRODUCTION',review:undefined}).success).toBe(false);}});
 it('records reference guidance as draft without granting art approval',()=>{expect(ArtDirectionSchema.parse(artDirection).status).toBe('DRAFT');expect(artDirection.referenceIds).toContain('omni');expect(assets.filter(a=>a.id.startsWith('tv-human-')).every(a=>a.status==='PROTOTYPE')).toBe(true);});
});
