import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const source=readFileSync('src/sim/physical/interactionSpec.json','utf8');
const spec=JSON.parse(source) as Record<string,string|number>;
const hash=createHash('sha256').update(JSON.stringify(spec)).digest('hex');
const header='// Generated by scripts/generate-interaction-spec.ts. Do not edit.\n#pragma once\nnamespace TVInteractionSpec {\n'+
  Object.entries(spec).map(([key,value])=>typeof value==='number'?`inline constexpr double ${key} = ${value};`:`inline constexpr const TCHAR* ${key} = TEXT("${value}");`).join('\n')+`\ninline constexpr const TCHAR* hash = TEXT("${hash}");\n}\n`;
const path='unreal/TornVeilOnline/Source/TornVeilOnline/TVInteractionSpec.generated.h';
if(process.argv.includes('--check')) {if(readFileSync(path,'utf8')!==header)throw new Error('Stale native interaction specification; regenerate');}
else writeFileSync(path,header);
console.log(hash);
const motion=JSON.parse(readFileSync('src/sim/physical/combatMotion.json','utf8')) as {
  attacks:Record<string,{samples:number[][]}>;duck:number[][];
};
const roundMotion=JSON.parse(readFileSync('src/sim/physical/combatRoundMotion.json','utf8')) as {samples:number[][]};
const roundV2=JSON.parse(readFileSync('src/sim/physical/combatRoundMotionV2.json','utf8')) as {samples:number[][]};
const rows=(name:string,data:number[][])=>`inline constexpr double ${name}[][${data[0].length}] = {${data.map(row=>`{${row.join(',')}}`).join(',')}};\n`;
const motionHeader='// Generated by scripts/generate-interaction-spec.ts. Do not edit.\n#pragma once\nnamespace TVCombatMotion {\n'+
 Object.entries(motion.attacks).map(([name,a])=>rows(name,a.samples)).join('')+rows('roundKick',roundMotion.samples)+rows('roundKickV2',roundV2.samples)+rows('posture',motion.duck)+`
inline FVector Strike(const FString& Variant,double T,int Revision=1) {
 const double (*P)[4]=Variant==TEXT("round")?(Revision==2?roundKickV2:roundKick):Variant==TEXT("kick")?kick:Variant==TEXT("hook")?hook:direct;
 const int N=Variant==TEXT("round")?(Revision==2?sizeof(roundKickV2)/sizeof(roundKickV2[0]):sizeof(roundKick)/sizeof(roundKick[0])):sizeof(direct)/sizeof(direct[0]);
 for(int I=1;I<N;++I)if(T<=P[I][0]){const double F=FMath::Clamp((T-P[I-1][0])/(P[I][0]-P[I-1][0]),0.,1.);return FMath::Lerp(FVector(P[I-1][1],P[I-1][2],P[I-1][3]),FVector(P[I][1],P[I][2],P[I][3]),F);}
 return FVector(P[N-1][1],P[N-1][2],P[N-1][3]);
}
inline double Duck(double T) {
 constexpr int N=sizeof(posture)/sizeof(posture[0]);if(T<0||T>posture[N-1][0])return 0;
 for(int I=1;I<N;++I)if(T<=posture[I][0])return FMath::Lerp(posture[I-1][1],posture[I][1],(T-posture[I-1][0])/(posture[I][0]-posture[I-1][0]));return 0;
}
}\n`;
const motionPath='unreal/TornVeilOnline/Source/TornVeilOnline/TVCombatMotion.generated.h';
if(process.argv.includes('--check')) {if(readFileSync(motionPath,'utf8')!==motionHeader)throw new Error('Stale native combat motion specification; regenerate');}
else writeFileSync(motionPath,motionHeader);

const repertoire=JSON.parse(readFileSync('src/sim/physical/combatRepertoire.json','utf8')) as {moves:Record<string,Record<string,string|number>>};
const repertoireV2=JSON.parse(readFileSync('src/sim/physical/combatRepertoireV2.json','utf8')) as typeof repertoire;
const numeric=['preparation','active','recovery','samplePreparation','sampleActive','sampleRecovery','attackAt','stepAt','postureAt','moveAt','chainStart'];
const rh=`// Generated by scripts/generate-interaction-spec.ts. Do not edit.
#pragma once
namespace TVCombatRepertoire {
struct FMove {const TCHAR* Id;const TCHAR* Variant;const TCHAR* Asset;const TCHAR* Effector;const TCHAR* ChainAsset;${numeric.map(n=>`double ${n};`).join('')}};
inline const FMove& Move(const FString& Id,int Revision=2) {
 ${[repertoire,repertoireV2].map((r,i)=>`static const FMove Moves${i+1}[]={${Object.entries(r.moves).map(([id,m])=>`{TEXT("${id}"),TEXT("${m.variant}"),TEXT("/Game/TornVeil/Combat/${m.asset}"),TEXT("${m.effector}"),TEXT("/Game/TornVeil/Combat/${m.chainAsset??m.asset}"),${numeric.map(n=>m[n]??0).join(',')}}`).join(',')}};`).join("\n")}
 const FMove* Moves=Revision==2?Moves2:Moves1;for(int I=0;I<4;++I)if(Id==Moves[I].Id)return Moves[I];return Moves[0];
}
}
`;
const rp='unreal/TornVeilOnline/Source/TornVeilOnline/TVCombatRepertoire.generated.h';
if(process.argv.includes('--check')){if(readFileSync(rp,'utf8')!==rh)throw new Error('Stale native combat repertoire');}else writeFileSync(rp,rh);
