import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const source=readFileSync('src/sim/physical/interactionSpec.json','utf8');
const spec=JSON.parse(source) as Record<string,string|number>;
const hash=createHash('sha256').update(JSON.stringify(spec)).digest('hex');
const header='// Generated by scripts/generate-interaction-spec.ts. Do not edit.\n#pragma once\nnamespace TVInteractionSpec {\n'+
  Object.entries(spec).map(([key,value])=>typeof value==='number'?`inline constexpr double ${key} = ${value};`:`inline constexpr const TCHAR* ${key} = TEXT("${value}");`).join('\n')+`\ninline constexpr const TCHAR* hash = TEXT("${hash}");\n}\n`;
const path='unreal/TornVeilOnline/Source/TornVeilOnline/TVInteractionSpec.generated.h';
if(process.argv.includes('--check')) {if(readFileSync(path,'utf8')!==header)throw new Error('Stale native interaction specification; regenerate');}
else writeFileSync(path,header);
console.log(hash);
