import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const source=readFileSync('src/sim/physical/interactionSpec.json','utf8');
const spec=JSON.parse(source) as Record<string,string|number>;
const hash=createHash('sha256').update(JSON.stringify(spec)).digest('hex');
const header='// Generated by scripts/generate-interaction-spec.ts. Do not edit.\n#pragma once\nnamespace TVInteractionSpec {\n'+
  Object.entries(spec).map(([key,value])=>typeof value==='number'?`inline constexpr double ${key} = ${value};`:`inline constexpr const TCHAR* ${key} = TEXT("${value}");`).join('\n')+`\ninline constexpr const TCHAR* hash = TEXT("${hash}");\n}\n`;
const path='unreal/TornVeilOnline/Source/TornVeilOnline/TVInteractionSpec.generated.h';
if(process.argv.includes('--check')) {if(readFileSync(path,'utf8')!==header)throw new Error('Stale native interaction specification; regenerate');}
else writeFileSync(path,header);
console.log(hash);
const motion=JSON.parse(readFileSync('src/sim/physical/combatMotion.json','utf8')) as {
  attacks:Record<string,{samples:number[][]}>;duck:number[][];
};
const rows=(name:string,data:number[][])=>`inline constexpr double ${name}[][${data[0].length}] = {${data.map(row=>`{${row.join(',')}}`).join(',')}};\n`;
const motionHeader='// Generated by scripts/generate-interaction-spec.ts. Do not edit.\n#pragma once\nnamespace TVCombatMotion {\n'+
 Object.entries(motion.attacks).map(([name,a])=>rows(name,a.samples)).join('')+rows('posture',motion.duck)+`
inline FVector Strike(const FString& Variant,double T) {
 const double (*P)[4]=Variant==TEXT("kick")?kick:Variant==TEXT("hook")?hook:direct;
 constexpr int N=sizeof(direct)/sizeof(direct[0]);
 for(int I=1;I<N;++I)if(T<=P[I][0]){const double F=FMath::Clamp((T-P[I-1][0])/(P[I][0]-P[I-1][0]),0.,1.);return FMath::Lerp(FVector(P[I-1][1],P[I-1][2],P[I-1][3]),FVector(P[I][1],P[I][2],P[I][3]),F);}
 return FVector(P[N-1][1],P[N-1][2],P[N-1][3]);
}
inline double Duck(double T) {
 constexpr int N=sizeof(posture)/sizeof(posture[0]);if(T<0||T>posture[N-1][0])return 0;
 for(int I=1;I<N;++I)if(T<=posture[I][0])return FMath::Lerp(posture[I-1][1],posture[I][1],(T-posture[I-1][0])/(posture[I][0]-posture[I-1][0]));return 0;
}
}\n`;
const motionPath='unreal/TornVeilOnline/Source/TornVeilOnline/TVCombatMotion.generated.h';
if(process.argv.includes('--check')) {if(readFileSync(motionPath,'utf8')!==motionHeader)throw new Error('Stale native combat motion specification; regenerate');}
else writeFileSync(motionPath,motionHeader);
